export default {
  6: {
    _id: 6,
    title: 'Lettre',
    text: 'On dirait un email d\'un certain "Maître Lombard" à BHL.',
    image: 'clue.png',
  },
  7: {
    _id: 7,
    title: 'Lettre',
    text: "Une lettre à BHL. Ça parle de Cagliostro. On dirait que ça vient d'une sorte de détective privé.",
    image: 'clue.png',
  },
  8: {
    _id: 8,
    title: 'Liste invités',
    text: 'Ce serait la liste des invités ? Mais il y a une personne en trop...',
    image: 'clue.png',
  },
  9: {
    _id: 9,
    title: 'Relevé',
    text: "Un relevé de comptes. On ne voit pas le nom, mais celui qui l'a ouvert a visiblement planqué de l'argent !",
    image: 'clue.png',
  },
  10: {
    _id: 10,
    title: 'Lettre',
    text: "C'est une lettre de Janet Bean, l'actrice, à BHL. Elle semble assez remontée contre lui.",
    image: 'clue.png',
  },
  11: {
    _id: 11,
    title: 'Lettre',
    text: "Un mot envoyé par BHL à un agent de Gollimard. Le destinataire n'est pas marqué mais ce serait peut être...",
    image: 'clue.png',
  },
  12: {
    _id: 12,
    title: 'Lettre',
    text: 'Une lettre envoyée par Grisha Dix à BHL',
    image: 'clue.png',
  },
  13: {
    _id: 13,
    title: 'Journal',
    text: "Un article sur ce qu'il s'est passé au cours d'une émission animée par Claire Chazelle, avec Cagliostro en invité. BHL n'a pas du apprécier...",
    image: 'clue.png',
  },
  14: {
    _id: 14,
    title: 'Journal',
    text: "Une critique littéraire de BHL sur le livre Banlieue Noire d'Ernestine Bougrel. Pas la plus flatteuse.",
    image: 'clue.png',
  },
  15: {
    _id: 15,
    title: 'Un Esprit Talkie',
    text: 'Un objet qui permet de communiquer avec les esprits.',
    image: 'clue.png',
  },
  16: {
    _id: 16,
    title: 'Lettre',
    text: "Elle a pas l'air commode, cette Giulia.",
    image: 'clue.png',
  },
  17: {
    _id: 17,
    title: 'Journal',
    text: 'Un article qui date du terrible drame de la Rue du Clinquet. La Main Noire est évoquée. Serait-elle vraiment impliquée ? ',
    image: 'clue.png',
  },
  18: {
    _id: 18,
    title: 'Journal',
    text: 'Un journal avec un article intéressant.',
    image: 'clue.png',
  },
  19: {
    _id: 19,
    title: 'Journal',
    text: 'Un journal avec un article intéressant.',
    image: 'clue.png',
  },
  20: {
    _id: 20,
    title: 'Journal',
    text: "Une liste de membres de la Main Noire.. Etonnant qu'il manque.... ?",
    image: 'clue.png',
  },
  21: {
    _id: 21,
    title: 'Valise',
    text: 'Cette valise porte une étiquette inhabituelle...',
    image: 'clue.png',
  },
  22: {
    _id: 22,
    title: 'Lettre',
    text: 'Le trois fois saint doit faire référence à Jaya Shakyamuni, son vrai nom étant Jésus Krishna Shakyamuni, portant le nom de trois saints... BHL a donc révélé des secrets des NEFILIM dans ses livres ?',
    image: 'clue.png',
  },
  23: {
    _id: 23,
    title: "Une carte d'identité militaire",
    text: 'Pas commode, le jeune françois.',
    image: 'clue.png',
  },
  24: {
    _id: 24,
    title: 'Un livre sur les sociétés du mal',
    text: 'Un livre qui traite du mal et de démonologie. Vous lisez des textes et trouvez un passage sur les lieutenants de Bélial, ainsi que des passages sur la Main Noire ; plus composée de bourgeois en manque de sensations que de sorciers, il semblerait que certains individus de ce groupe soient tout de même plutôt capables ! Les membres en sont secrets. ',
    image: 'clue.png',
  },
  25: {
    _id: 25,
    title: 'Article',
    text: 'Un journal avec un article intéressant.',
    image: 'clue.png',
  },
  26: { _id: 26, title: 'Carnet', text: 'Un carnet.', image: 'clue.png' },
  27: {
    _id: 27,
    title: 'Lettre',
    text: 'Une lettre. Qui est donc cet expéditeur ? Et de quoi parle-t-il ?',
    image: 'clue.png',
  },
  28: {
    _id: 28,
    title: 'Une salle de bains.',
    text: "Hmmm, la vapeur d'eau en sortant de la douche...",
    image: 'clue.png',
  },
  29: {
    _id: 29,
    title: 'Des puzzles !',
    text: 'Je déteste les puzzles.',
    image: 'clue.png',
  },
  30: {
    _id: 30,
    title: 'Livre',
    text: 'Un super bouquin de science fiction.',
    image: 'clue.png',
  },
  31: {
    _id: 31,
    title: 'Livre',
    text: 'Un bon livre, un peu daté mais palpitant.',
    image: 'clue.png',
  },
  32: {
    _id: 32,
    title: 'Un livre intéressant',
    text: 'Il y a quelque chose dans ce livre... Ça semble être une recommandation ?',
    image: 'clue.png',
  },
  33: {
    _id: 33,
    title: 'Un livre trésor',
    text: 'Il y a quelque chose dans ce livre...',
    image: 'clue.png',
  },
  34: {
    _id: 34,
    title: 'Un post it',
    text: "Hmmm.... Intéressant, mais je ne vois pas à quoi ça sert pour l'instant...",
    image: 'clue.png',
  },
  35: {
    _id: 35,
    title: 'Une liste',
    text: 'Des parfums et senteurs...',
    image: 'clue.png',
  },
  36: {
    _id: 36,
    title: 'Une belle armoire.',
    text: 'Elle semble fermé à clef, qui ne doit pas être loin...',
    image: 'clue.png',
  },
  37: {
    _id: 37,
    title: 'Un puzzle !',
    text: "Si on faisait un puzzle ? Lui a l'air rapide à faire.",
    image: 'clue.png',
  },
  38: {
    _id: 38,
    title: 'Un chapeau de medium.',
    text: "C'est un chapeau utile pour faire des séances de spiritisme.",
    image: 'clue.png',
  },
  39: {
    _id: 39,
    title: 'Un livre sur le spiritisme.',
    text: "Vous trouvez un document à l'intérieur qui vous apprend comment faire une séance de spiritisme. Sensass !",
    image: 'clue.png',
  },
  40: {
    _id: 40,
    title: 'Un livre sur les sociétés secrètes.',
    text: 'Vous lisez un passage sur les NEFILIM, une secte profondément malfaisante dont les gourous lavent le cerveau et abusent de leurs infortunés adeptes.',
    image: 'clue.png',
  },
  41: {
    _id: 41,
    title: 'Un livre sur la sorcellerie et la possession.',
    text: "Vous en apprenez plus sur la révocation et l'invocation des démons. A l'intérieur, un document résume comment procéder à la révocation d'un démon.",
    image: 'clue.png',
  },
  code_91D3: {
    _id: 'code_91D3',
    title: 'Miroir, mon beau miroir',
    text: "Vous êtes attirés par le théâtre d'enfants à gauche de la chambre en entrant. Dans une marionnette il semblerait y avoir quelque chose d'intéressant...",
    image: 'unlocked.png',
  },
  code_2951: {
    _id: 'code_2951',
    title: 'Un nez, et quel nez !',
    text: 'Le savoir se trouve derrière les bibliothèques.',
    image: 'unlocked.png',
  },
};
